import Link from "next/link";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";
import { requireAdminUser } from "@/lib/supabase/auth";
import { updateCommunityVerification } from "@/features/moderation/trust-actions";

type PageProps = { searchParams: Promise<{ status?: string }> };

export default async function AdminVerificationPage({ searchParams }: PageProps) {
  await requireAdminUser();
  const supabase = createAdminSupabaseClient();
  const { data: communities, error } = await supabase.from("communities").select("id,name,slug,status,verification_status,last_verified_at,health_status,member_count,updated_at").eq("status", "published").order("updated_at", { ascending: false }).limit(100);
  const query = await searchParams;
  return <main className="admin-page"><header className="admin-header"><div><Link href="/admin" className="back-link">← Back to control center</Link><p className="eyebrow">CHATSCOUT TRUST & SAFETY</p><h1>Verification center</h1><p>Confirm which published communities have passed a platform verification review.</p></div></header>{query.status === "updated" && <p className="form-message success">Verification status updated.</p>}{query.status === "failed" && <p className="form-message error">Unable to update verification status.</p>}{error && <p className="form-message error">Verification data is temporarily unavailable.</p>}{(communities ?? []).map((community) => <article className="admin-record-card" key={community.id}><div className="admin-record-main"><div className="admin-record-heading"><span className={`admin-status-badge ${community.verification_status}`}>{community.verification_status.replace("_", " ")}</span><h3>{community.name}</h3><p>Health: {community.health_status.replace("_", " ")} · {community.member_count?.toLocaleString("en-IN") ?? "Member count unavailable"} members</p></div><dl className="admin-meta-grid"><div><dt>Last verified</dt><dd>{community.last_verified_at ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(community.last_verified_at)) : "Never"}</dd></div><div><dt>Community</dt><dd><Link href={`/community/${community.slug}`} target="_blank">Open public page</Link></dd></div></dl></div><aside className="admin-actions-panel"><form action={updateCommunityVerification}><input type="hidden" name="communityId" value={community.id} /><input type="hidden" name="verificationStatus" value="verified" /><input name="note" maxLength={2000} placeholder="Verification note" /><button className="primary-button form-submit" type="submit">Mark verified</button></form><form action={updateCommunityVerification}><input type="hidden" name="communityId" value={community.id} /><input type="hidden" name="verificationStatus" value="needs_review" /><button className="admin-secondary" type="submit">Needs review</button></form><form action={updateCommunityVerification}><input type="hidden" name="communityId" value={community.id} /><input type="hidden" name="verificationStatus" value="broken" /><button className="admin-danger" type="submit">Mark broken</button></form><form action={updateCommunityVerification}><input type="hidden" name="communityId" value={community.id} /><input type="hidden" name="verificationStatus" value="unverified" /><button className="admin-secondary" type="submit">Reset</button></form></aside></article>)}</main>;
}
