import Link from 'next/link';
import { requireBrand } from '@/lib/brand/authorization';
import { createAdminSupabaseClient } from '@/lib/supabase/admin';
import { submitCampaign } from '@/features/brand/actions';

const labels:Record<string,string>={draft:'Draft',pending_review:'Pending review',active:'Active',paused:'Paused',completed:'Completed',cancelled:'Cancelled'};
export default async function BrandCampaignsPage(){
 const brand=await requireBrand();const db=createAdminSupabaseClient() as any;const {data:campaigns}=await db.from('campaigns').select('*').eq('brand_user_id',brand.user.id).order('created_at',{ascending:false});const ids=(campaigns??[]).map((c:any)=>c.id);const [{data:parts},{data:deliverables},{data:subs},{data:matchRows}]=await Promise.all([ids.length?db.from('campaign_participations').select('campaign_id,status,reward_status').in('campaign_id',ids):Promise.resolve({data:[]}),ids.length?db.from('campaign_deliverables').select('campaign_id,id,required').in('campaign_id',ids):Promise.resolve({data:[]}),ids.length?db.from('campaign_submissions').select('participation_id,status').limit(1000):Promise.resolve({data:[]}),ids.length?db.from('campaign_community_matches').select('campaign_id,admin_response,invited_at').in('campaign_id',ids):Promise.resolve({data:[]})]);
 return <main className="page-content"><header className="owner-header"><div><Link href="/brand" className="back-link">← Brand dashboard</Link><p className="eyebrow">CAMPAIGNS</p><h1>Your campaigns</h1><p>Draft, submit, activate and monitor real campaigns without fabricating execution metrics.</p></div><Link className="primary-button" href="/brand/campaigns/new">Create campaign</Link></header><section className="section"><div className="grid">{campaigns?.map((c:any)=>{const ps=(parts??[]).filter((p:any)=>p.campaign_id===c.id);const ds=(deliverables??[]).filter((d:any)=>d.campaign_id===c.id);const pendingProof=ps.length?(subs??[]).filter((s:any)=>ps.some((p:any)=>s.participation_id===p.id)&&s.status==='submitted').length:0;const mm=(matchRows??[]).filter((m:any)=>m.campaign_id===c.id);const invited=mm.filter((m:any)=>m.invited_at).length;const accepted=mm.filter((m:any)=>m.admin_response==='accepted').length;return <article className="card" key={c.id}><div className="cardBody"><div className="cardTop"><span className="badge">{labels[c.status]??c.status}</span><span className="badge">₹{Number(c.total_budget??0).toLocaleString('en-IN')}</span></div><h3>{c.title}</h3><p>{c.objective}</p><div className="meta">{ds.length} deliverables · {ps.length} participations · {pendingProof} proof awaiting review</div><div className="meta">{mm.length} ranked matches · {invited} invited · {accepted} accepted</div><div className="meta">Created {new Date(c.created_at).toLocaleDateString('en-IN')}{c.application_deadline?` · Deadline ${new Date(c.application_deadline).toLocaleDateString('en-IN')}`:''}</div><div className="cardLinks"><Link className="view" href={`/brand/campaigns/${c.id}/edit`}>Edit →</Link><Link className="view" href={`/brand/campaigns/${c.id}/matches`}>Audience matches →</Link><Link className="view" href={`/brand/campaigns/${c.id}/submissions`}>Execution & submissions →</Link><Link className="view" href={`/brand/applications?campaign=${encodeURIComponent(c.id)}`}>Applications →</Link>{c.status==='draft'&&<form action={submitCampaign}><input type="hidden" name="campaignId" value={c.id}/><button className="admin-secondary" type="submit">Submit for review</button></form>}</div></div></article>})}{!campaigns?.length&&<div className="empty"><h3>Create your first campaign.</h3><p>There are no campaigns yet. No demo campaigns are inserted.</p><Link className="primary-button" href="/brand/campaigns/new">Create campaign</Link></div>}</div></section></main>;
}
