import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { createServerAuthClient } from '@/lib/supabase/auth';
import { createAdminSupabaseClient } from '@/lib/supabase/admin';
import { startParticipation, startDeliverable, submitDeliverable } from '@/features/campaign-execution/actions';

const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
function daysRemaining(date:string|null){if(!date)return null;return Math.ceil((new Date(date).getTime()-Date.now())/86400000);}

export default async function CampaignWorkspace({params}:{params:Promise<{campaignId:string}>}){
 const auth=await createServerAuthClient();const {data:{user}}=await auth.auth.getUser();if(!user)redirect('/submit/login?error=auth');
 const {campaignId}=await params;const db=createAdminSupabaseClient() as any;
 const {data:p}=await db.from('campaign_participations').select('*').eq('campaign_id',campaignId).eq('admin_user_id',user.id).maybeSingle();if(!p)notFound();
 const participation:any=p;
 const [{data:c},{data:deliverables},{data:progress},{data:submissions},{data:community}]=await Promise.all([
  db.from('campaigns').select('*').eq('id',campaignId).maybeSingle(),
  db.from('campaign_deliverables').select('*').eq('campaign_id',campaignId).order('display_order'),
  db.from('campaign_deliverable_progress').select('*').eq('participation_id',participation.id),
  db.from('campaign_submissions').select('*').eq('participation_id',participation.id).order('deliverable_id').order('version_no',{ascending:false}),
  db.from('communities').select('id,name,slug,platform,member_count').eq('id',participation.community_id).maybeSingle()
 ]);
 if(!c)notFound();
 const campaign:any=c;
 const {data:ownerBrand}=await db.from('brand_profiles').select('company_name,website,logo_url').eq('user_id',campaign.brand_user_id).maybeSingle();
 const progressBy=new Map((progress??[]).map((x:any)=>[x.deliverable_id,x]));const latestBy=new Map<string,any>();for(const s of submissions??[]){if(!latestBy.has(s.deliverable_id))latestBy.set(s.deliverable_id,s);}
 const deadline= campaign.ends_at ?? null;const remaining=daysRemaining(deadline);
 return <main className="page-content"><header className="owner-header"><div><Link href="/dashboard/rewards" className="back-link">← Community Rewards</Link><p className="eyebrow">CAMPAIGN WORKSPACE</p><h1>{campaign.title}</h1><p>{campaign.description}</p></div><div className="cardTop"><span className="badge">{label(participation.status)}</span><span className="badge">{participation.reward_status==='approved'?'REWARD APPROVED':`₹${Number(participation.committed_reward??0).toLocaleString('en-IN')}`}</span></div></header>
 <section className="trust-strip"><div><div className="trust-icon">₹</div><b>{Number(participation.committed_reward??0).toLocaleString('en-IN')} INR</b><small>Committed reward</small></div><div><div className="trust-icon">◷</div><b>{campaign.ends_at?new Date(campaign.ends_at).toLocaleDateString('en-IN'): 'No end date'}</b><small>{remaining===null?'Campaign end':remaining<0?'Overdue':`${remaining} days remaining`}</small></div><div><div className="trust-icon">✓</div><b>{community?.name??'Your community'}</b><small>{ownerBrand?.company_name??'Brand'} · {community?.platform??''}</small></div></section>
 {participation.status==='selected'||participation.status==='ready'?<section className="form-panel" style={{marginBottom:24}}><p className="eyebrow">READY TO START</p><h2>Campaign instructions</h2><p>{campaign.instructions||'Follow each deliverable below. Complete every required task and submit the requested proof.'}</p>{campaign.requirements&&<><h3>Target requirements</h3><p>{campaign.requirements}</p></>}<form action={startParticipation}><input type="hidden" name="participationId" value={participation.id}/><input type="hidden" name="campaignId" value={campaignId}/><button className="primary-button list-button" type="submit">Start Campaign</button></form></section>:<section className="form-panel" style={{marginBottom:24}}><p className="eyebrow">CAMPAIGN INSTRUCTIONS</p><h2>{ownerBrand?.company_name??'Brand'} brief</h2><p>{campaign.instructions||'Complete the listed deliverables and submit proof.'}</p>{campaign.deliverables_description&&<><h3>Deliverable overview</h3><p>{campaign.deliverables_description}</p></>}</section>}
 <section><div className="section-heading"><div><p className="eyebrow">DELIVERABLES</p><h2>Tasks & proof</h2></div></div>{(deliverables??[]).length?<div className="community-grid">{(deliverables??[]).map((d:any)=>{const pr=progressBy.get(d.id);const latest=latestBy.get(d.id);return <article className="community-card" key={d.id}><div className="community-info"><div className="community-title-row"><h3>{d.title}</h3><span className="demo-pill">{d.required?'Required':'Optional'}</span></div><div className="tag-row"><span>{label(d.type)}</span><span>{label(pr?.status??'not_started')}</span></div>{d.description&&<p className="community-description" style={{minHeight:'auto'}}>{d.description}</p>}
 {d.instructions&&<div className="form-note"><strong>Instructions:</strong> {d.instructions}</div>}{d.required_text&&<div className="form-note"><strong>Required text:</strong> {d.required_text}</div>}{d.timing&&<div className="form-note"><strong>Timing:</strong> {d.timing}</div>}{d.destination_url&&<p className="meta">Destination: <a href={d.destination_url} target="_blank" rel="noreferrer">Open link ↗</a></p>}{d.tracking_url&&<p className="meta">Tracking: <a href={d.tracking_url} target="_blank" rel="noreferrer">Open tracking link ↗</a></p>}{d.prohibited_modifications&&<div className="form-note"><strong>Do not modify:</strong> {d.prohibited_modifications}</div>}
 {latest&&<div className="form-note"><strong>Latest submission:</strong> v{latest.version_no} · {label(latest.status)}{latest.review_reason&&<> · {latest.review_reason}</>}{latest.content&&<div style={{marginTop:6}}>{latest.content}</div>}</div>}
 {d.deadline&&<p className="meta">Deadline: {new Date(d.deadline).toLocaleString('en-IN')}</p>}
 {(pr?.status==='not_started'||pr?.status==='revision_required')&&<form action={startDeliverable}><input type="hidden" name="participationId" value={participation.id}/><input type="hidden" name="deliverableId" value={d.id}/><input type="hidden" name="campaignId" value={campaignId}/><button className="admin-secondary" type="submit">{pr?.status==='revision_required'?'Work on revision':'Start deliverable'}</button></form>}
 {(pr?.status==='in_progress'||pr?.status==='revision_required'||pr?.status==='resubmitted'||pr?.status==='submitted')&&latest?.status!=='approved'&&latest?.status!=='rejected'&&<form action={submitDeliverable} encType="multipart/form-data" style={{display:'grid',gap:8,marginTop:10}}><input type="hidden" name="participationId" value={participation.id}/><input type="hidden" name="deliverableId" value={d.id}/><input type="hidden" name="campaignId" value={campaignId}/><label>Proof type<select name="submissionType" defaultValue={d.type.includes('story')||d.type.includes('post')?'screenshot':'url'}><option value="screenshot">Screenshot</option><option value="url">URL</option><option value="platform_url">Platform post/message URL</option><option value="text_note">Text note</option><option value="metric">Basic metric</option></select></label><label>Proof file<input name="proofFile" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" /></label><label>Note / URL<input name="content" placeholder="Paste URL or add a short note" /></label><label>Metric value (optional)<input name="metricValue" type="number" min="0" step="0.01" /></label><button className="primary-button list-button" type="submit">Submit Deliverable</button></form>}
 </div></article>})}</div>:<div className="empty"><h3>No deliverables configured.</h3><p>The brand must add at least one task before execution can begin.</p></div>}</section>
 <section className="section"><div className="empty"><h3>Reward status: {label(participation.reward_status)}</h3><p>An approved reward is an internal Community Rewards ledger credit. Phase 3 does not transfer money to a bank or UPI account.</p></div></section>
 </main>;
}