import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireBrand } from '@/lib/brand/authorization';
import { createAdminSupabaseClient } from '@/lib/supabase/admin';
import { saveCampaign } from '@/features/brand/actions';
import { DeliverablesEditor } from '@/components/brand/deliverables-editor';

type Props={params:Promise<{id:string}>};
export default async function EditCampaignPage({params}:Props){
 const brand=await requireBrand();const {id}=await params;const db=createAdminSupabaseClient() as any;
 const {data:c}=await db.from('campaigns').select('*').eq('id',id).eq('brand_user_id',brand.user.id).maybeSingle();if(!c)notFound();
 const {data:categories}=await db.from('categories').select('id,name').eq('is_active',true).order('display_order',{ascending:true}).order('name');
 const {data:ds}=await db.from('campaign_deliverables').select('*').eq('campaign_id',id).order('display_order');
 const initial=(ds??[]).map((d:any)=>({title:d.title,description:d.description,type:d.type,required:d.required,deadline:d.deadline?new Date(d.deadline).toISOString().slice(0,16):'',rewardAmount:d.reward_amount?.toString()??'',instructions:d.instructions??'',requiredText:d.required_text??'',destinationUrl:d.destination_url??'',trackingUrl:d.tracking_url??'',contentRequirements:d.content_requirements??'',prohibitedModifications:d.prohibited_modifications??'',timing:d.timing??'',submissionRequirements:d.submission_requirements??''}));
 return <main className="page-content"><section className="form-panel"><Link href="/brand/campaigns" className="back-link">← Campaigns</Link><p className="eyebrow">EDIT CAMPAIGN</p><h1>{c.title}</h1><p className="form-note">Only draft and pending-review campaigns can be edited. Once active, execution records are immutable.</p><form action={saveCampaign} className="form-grid"><input type="hidden" name="id" value={c.id}/>
  <label>Campaign name<input required name="title" defaultValue={c.title}/></label><label>Objective<input required name="objective" defaultValue={c.objective}/></label><label>Category<select name="categoryId" defaultValue={c.category_id??''}><option value="">Any category</option>{categories?.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Platforms<input name="platforms" defaultValue={(c.target_platforms??[]).join(', ')}/></label><label>Languages<input name="languages" defaultValue={(c.target_languages??[]).join(', ')}/></label><label>Regions<input name="regions" defaultValue={(c.target_regions??[]).join(', ')}/></label>
  <label>Min members<input name="minMembers" type="number" min="0" defaultValue={c.min_member_count??''}/></label><label>Max members<input name="maxMembers" type="number" min="0" defaultValue={c.max_member_count??''}/></label><label>Total budget<input required name="budget" type="number" min="0" step="0.01" defaultValue={c.total_budget??0}/></label><label>Reward model<select name="rewardModel" defaultValue={c.reward_model}><option value="fixed">Fixed</option><option value="range">Range</option><option value="custom">Custom</option></select></label><label>Reward / community<input name="rewardPerCommunity" type="number" min="0" step="0.01" defaultValue={c.reward_per_community??''}/></label><label>Reward min<input name="rewardMin" type="number" min="0" step="0.01" defaultValue={c.reward_min??''}/></label><label>Reward max<input name="rewardMax" type="number" min="0" step="0.01" defaultValue={c.reward_max??''}/></label><label>Starts<input name="startsAt" type="datetime-local" defaultValue={c.starts_at?new Date(c.starts_at).toISOString().slice(0,16):''}/></label><label>Ends<input name="endsAt" type="datetime-local" defaultValue={c.ends_at?new Date(c.ends_at).toISOString().slice(0,16):''}/></label><label>Application deadline<input name="deadline" type="datetime-local" defaultValue={c.application_deadline?new Date(c.application_deadline).toISOString().slice(0,16):''}/></label>
  <label className="full">Description<textarea required name="description" rows={5} defaultValue={c.description}/></label><label className="full">Campaign instructions<textarea name="instructions" rows={5} defaultValue={c.instructions??''}/></label><label className="full">Target requirements<textarea name="requirements" rows={4} defaultValue={c.requirements??''}/></label><label className="full">Deliverable overview<textarea name="deliverables" rows={3} defaultValue={c.deliverables_description??''}/></label>
  <DeliverablesEditor initial={initial}/><label className="check-row"><input name="requireVerified" type="checkbox" defaultChecked={c.require_verified}/> Require verified communities</label><label className="check-row"><input name="requireHealthy" type="checkbox" defaultChecked={c.require_healthy}/> Require healthy communities</label>
  <div className="form-actions full"><Link className="admin-secondary" href="/brand/campaigns">Cancel</Link><button className="primary-button" type="submit">Save changes</button></div>
 </form></section></main>;
}
