import Link from "next/link";
import { notFound } from "next/navigation";
import { ControllerShell } from "@/components/admin/controller-shell";
import { CommunityEditForm } from "@/components/admin/community-edit-form";
import { getQualityCommunityForAdmin } from "@/features/quality/data-access";
import { requireAdminUser } from "@/lib/supabase/auth";
import type { QualityIssue } from "@/features/quality/data-access";
export const dynamic="force-dynamic";
type Props={params:Promise<{id:string}>};
function issues(value:unknown):QualityIssue[]{return Array.isArray(value)?value as QualityIssue[]:[];}
export default async function QualityDetailPage({params}:Props){await requireAdminUser();const{id}=await params;const community=await getQualityCommunityForAdmin(id);if(!community)notFound();const list=issues(community.quality_issues);return <ControllerShell active="quality" title={community.name} description="Manual quality review and listing repair."><div className="quality-detail-grid"><section className="admin-section"><div className="quality-detail-score"><span className={"quality-grade "+(community.quality_grade??"unscored")}>{community.quality_grade??"Unscored"}</span><strong>{community.quality_score===null?"—":String(community.quality_score)+"/100"}</strong></div><p><Link href="/admin/quality">← Back to Quality Queue</Link> · <Link href={"/community/"+community.slug} target="_blank">Open public page ↗</Link></p><h2>Detected issues</h2>{list.length?<div className="quality-detail-issues">{list.map(issue=><article key={issue.code}><b>{issue.code.replaceAll("_"," ")}</b><span>{issue.severity}</span><p>{issue.message}</p></article>)}</div>:<p>No current quality issues.</p>}<dl className="admin-meta-grid"><div><dt>Platform</dt><dd>{community.platform}</dd></div><div><dt>Members</dt><dd>{community.member_count?.toLocaleString("en-IN")??"Unknown"}</dd></div><div><dt>Language</dt><dd>{community.language??"Unknown"}</dd></div><div><dt>Region</dt><dd>{community.region??"Unknown"}</dd></div><div><dt>Health</dt><dd>{community.health_status.replace("_"," ")}</dd></div><div><dt>Verification</dt><dd>{community.verification_status.replace("_"," ")}</dd></div></dl></section><section className="admin-section"><p className="eyebrow">FIX THE RECORD</p><h2>Admin editor</h2><p>Saving an edit automatically invalidates the quality score for a fresh scan.</p><CommunityEditForm community={community}/></section></div></ControllerShell>;}
