// Temporary hand-maintained representation of the Step 3A schema.
// Replace with `supabase gen types typescript` when CLI project authentication is available.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type CommunityStatus = "draft" | "pending" | "published" | "suspended" | "archived";
export type VerificationStatus = "unverified" | "verified" | "needs_review" | "broken";
export type SubmissionStatus = "pending" | "approved" | "rejected" | "needs_changes";
export type ReportType = "broken_link" | "spam" | "scam" | "misleading" | "other";
export type ReportStatus = "open" | "resolved" | "dismissed";
export type VerificationCheckType = "invite_link";
export type VerificationCheckStatus = "passed" | "failed" | "unknown";
export type AnalyticsEventName = "search" | "category_view" | "community_view" | "join_click";

export type Database = {
  public: {
    Tables: {
      categories: { Row: { id: string; name: string; slug: string; description: string | null; icon_key: string | null; sort_order: number; is_active: boolean; created_at: string; updated_at: string }; Insert: { id?: string; name: string; slug: string; description?: string | null; icon_key?: string | null; sort_order?: number; is_active?: boolean; created_at?: string; updated_at?: string }; Update: { id?: string; name?: string; slug?: string; description?: string | null; icon_key?: string | null; sort_order?: number; is_active?: boolean; created_at?: string; updated_at?: string }; Relationships: [] };
      communities: { Row: { id: string; name: string; slug: string; platform: "instagram"; invite_url: string; image_path: string | null; description: string; community_rules: string | null; age_restriction: string | null; eligibility: string | null; restrictions: string | null; language: string | null; region: string | null; member_count: number | null; status: CommunityStatus; verification_status: VerificationStatus; last_verified_at: string | null; typical_approval_time_minutes: number | null; created_at: string; updated_at: string; published_at: string | null }; Insert: { id?: string; name: string; slug: string; platform?: "instagram"; invite_url: string; image_path?: string | null; description: string; community_rules?: string | null; age_restriction?: string | null; eligibility?: string | null; restrictions?: string | null; language?: string | null; region?: string | null; member_count?: number | null; status?: CommunityStatus; verification_status?: VerificationStatus; last_verified_at?: string | null; typical_approval_time_minutes?: number | null; created_at?: string; updated_at?: string; published_at?: string | null }; Update: { id?: string; name?: string; slug?: string; platform?: "instagram"; invite_url?: string; image_path?: string | null; description?: string; community_rules?: string | null; age_restriction?: string | null; eligibility?: string | null; restrictions?: string | null; language?: string | null; region?: string | null; member_count?: number | null; status?: CommunityStatus; verification_status?: VerificationStatus; last_verified_at?: string | null; typical_approval_time_minutes?: number | null; created_at?: string; updated_at?: string; published_at?: string | null }; Relationships: [] };
      community_categories: { Row: { community_id: string; category_id: string }; Insert: { community_id: string; category_id: string }; Update: { community_id?: string; category_id?: string }; Relationships: [{ foreignKeyName: "community_categories_category_id_fkey"; columns: ["category_id"]; referencedRelation: "categories"; referencedColumns: ["id"] }, { foreignKeyName: "community_categories_community_id_fkey"; columns: ["community_id"]; referencedRelation: "communities"; referencedColumns: ["id"] }] };
      submissions: { Row: { id: string; community_name: string; invite_url: string; image_path: string | null; description: string; community_rules: string | null; age_restriction: string | null; eligibility: string | null; restrictions: string | null; category: string | null; language: string | null; region: string | null; approximate_member_count: number | null; submitter_contact: string | null; submitter_platform_identifier: string | null; submitter_user_id: string | null; status: SubmissionStatus; review_notes: string | null; reviewed_at: string | null; reviewed_by: string | null; created_at: string; updated_at: string }; Insert: { id?: string; community_name: string; invite_url: string; image_path?: string | null; description: string; community_rules?: string | null; age_restriction?: string | null; eligibility?: string | null; restrictions?: string | null; category?: string | null; language?: string | null; region?: string | null; approximate_member_count?: number | null; submitter_contact?: string | null; submitter_platform_identifier?: string | null; submitter_user_id?: string | null; status?: SubmissionStatus; review_notes?: string | null; reviewed_at?: string | null; reviewed_by?: string | null; created_at?: string; updated_at?: string }; Update: { id?: string; community_name?: string; invite_url?: string; image_path?: string | null; description?: string; community_rules?: string | null; age_restriction?: string | null; eligibility?: string | null; restrictions?: string | null; category?: string | null; language?: string | null; region?: string |null; approximate_member_count?: number | null; submitter_contact?: string | null; submitter_platform_identifier?: string | null; submitter_user_id?: string | null; status?: SubmissionStatus; review_notes?: string | null; reviewed_at?: string | null; reviewed_by?: string | null; created_at?: string; updated_at?: string }; Relationships: [] };
      reports: { Row: { id: string; community_id: string; report_type: ReportType; description: string | null; status: ReportStatus; created_at: string; resolved_at: string | null; resolved_by: string | null }; Insert: { id?: string; community_id: string; report_type: ReportType; description?: string | null; status?: ReportStatus; created_at?: string; resolved_at?: string | null; resolved_by?: string | null }; Update: { id?: string; community_id?: string; report_type?: ReportType; description?: string | null; status?: ReportStatus; created_at?: string; resolved_at?: string | null; resolved_by?: string | null }; Relationships: [{ foreignKeyName: "reports_community_id_fkey"; columns: ["community_id"]; referencedRelation: "communities"; referencedColumns: ["id"] }] };
      verification_checks: { Row: { id: string; community_id: string; check_type: VerificationCheckType; status: VerificationCheckStatus; checked_at: string; details: Json | null; created_at: string }; Insert: { id?: string; community_id: string; check_type: VerificationCheckType; status?: VerificationCheckStatus; checked_at?: string; details?: Json | null; created_at?: string }; Update: { id?: string; community_id?: string; check_type?: VerificationCheckType; status?: VerificationCheckStatus; checked_at?: string; details?: Json | null; created_at?: string }; Relationships: [{ foreignKeyName: "verification_checks_community_id_fkey"; columns: ["community_id"]; referencedRelation: "communities"; referencedColumns: ["id"] }] };
      analytics_events: { Row: { id: string; event_name: AnalyticsEventName; community_id: string | null; category_id: string | null; anonymous_session_id: string | null; metadata: Json | null; occurred_at: string }; Insert: { id?: string; event_name: AnalyticsEventName; community_id?: string | null; category_id?: string | null; anonymous_session_id?: string | null; metadata?: Json | null; occurred_at?: string }; Update: { id?: string; event_name?: AnalyticsEventName; community_id?: string | null; category_id?: string | null; anonymous_session_id?: string | null; metadata?: Json | null; occurred_at?: string }; Relationships: [{ foreignKeyName: "analytics_events_category_id_fkey"; columns: ["category_id"]; referencedRelation: "categories"; referencedColumns: ["id"] }, { foreignKeyName: "analytics_events_community_id_fkey"; columns: ["community_id"]; referencedRelation: "communities"; referencedColumns: ["id"] }] };
    };
    Views: Record<string, never>;
    Functions: { set_updated_at: { Args: Record<string, never>; Returns: unknown } };
    Enums: { community_status: CommunityStatus; verification_status: VerificationStatus; submission_status: SubmissionStatus; report_type: ReportType; report_status: ReportStatus; verification_check_type: VerificationCheckType; verification_check_status: VerificationCheckStatus; analytics_event_name: AnalyticsEventName };
    CompositeTypes: Record<string, never>;
  };
};

export type CategoryRow = Database["public"]["Tables"]["categories"]["Row"];
export type CommunityRow = Database["public"]["Tables"]["communities"]["Row"];
