import "server-only";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";
import { getPublishedCommunityImageUrl } from "@/lib/supabase/community-images";
import type { AdminCommunityItem } from "@/features/moderation/data-access";
import type { CommunityPlatform, CommunityQualityGrade, CommunityRow } from "@/types/database";

export type QualityIssue={code:string;severity:"critical"|"high"|"medium"|"low"|"info";message:string};
export type QualityQueueCommunity=Pick<CommunityRow,"id"|"name"|"slug"|"platform"|"description"|"language"|"region"|"member_count"|"health_status"|"health_last_checked_at"|"verification_status"|"quality_score"|"quality_grade"|"quality_issues"|"quality_checked_at"|"quality_reviewed_at"|"flag_reason"|"image_path"|"external_image_url">&{category:string|null;imageUrl:string|null;issues:QualityIssue[]};
export type QualityOverview={critical:number;needsReview:number;generic:number;good:number;unscored:number;outstanding:number};
const ISSUE_CODES=new Set(["missing_invite_url","indirect_join_url","duplicate_url","missing_category","category_mismatch","short_description","generic_description","missing_language","language_detected","language_mismatch","missing_region","missing_member_count","missing_image","health_inactive","health_needs_recheck","health_unknown","verification_broken","unverified","content_safety"]);
function issueList(value:unknown):QualityIssue[]{if(!Array.isArray(value))return[];return value.filter((item):item is QualityIssue=>{if(!item||typeof item!=="object")return false;const x=item as Record<string,unknown>;return typeof x.code==="string"&&typeof x.message==="string"&&["critical","high","medium","low","info"].includes(String(x.severity));});}
function safeTerm(value:string){return value.trim().replace(/[%_(),.]/g," ").replace(/\s+/g," ").slice(0,100);}
async function categoryMap(ids:string[]){if(!ids.length)return new Map<string,string>();const s=createAdminSupabaseClient();const{data:links}=await s.from("community_categories").select("community_id,category_id").in("community_id",ids);const cids=[...new Set((links??[]).map(x=>x.category_id))];if(!cids.length)return new Map<string,string>();const{data:cats}=await s.from("categories").select("id,name").in("id",cids);const names=new Map((cats??[]).map(x=>[x.id,x.name]));const out=new Map<string,string>();for(const link of links??[]){const name=names.get(link.category_id);if(name&&!out.has(link.community_id))out.set(link.community_id,name);}return out;}
export async function getQualityOverview():Promise<QualityOverview|null>{const s=createAdminSupabaseClient();const[critical,needsReview,generic,good,unscored,outstanding]=await Promise.all([s.from("communities").select("id",{count:"exact",head:true}).eq("status","published").eq("quality_grade","critical"),s.from("communities").select("id",{count:"exact",head:true}).eq("status","published").eq("quality_grade","needs_review"),s.from("communities").select("id",{count:"exact",head:true}).eq("status","published").eq("quality_grade","generic"),s.from("communities").select("id",{count:"exact",head:true}).eq("status","published").eq("quality_grade","good"),s.from("communities").select("id",{count:"exact",head:true}).eq("status","published").is("quality_grade",null),s.from("communities").select("id",{count:"exact",head:true}).eq("status","published").in("quality_grade",["critical","needs_review","generic"]).is("quality_reviewed_at",null)]);if([critical,needsReview,generic,good,unscored,outstanding].some(x=>x.error))return null;return{critical:critical.count??0,needsReview:needsReview.count??0,generic:generic.count??0,good:good.count??0,unscored:unscored.count??0,outstanding:outstanding.count??0};}
export async function getQualityQueue(input:{platform?:CommunityPlatform;grade?:CommunityQualityGrade|"unscored";issue?:string;q?:string;review?:"outstanding"|"all";limit?:number}):Promise<QualityQueueCommunity[]>{const s=createAdminSupabaseClient();const issue=input.issue&&ISSUE_CODES.has(input.issue)?input.issue:null;const term=safeTerm(input.q??"");let q=s.from("communities").select("id,name,slug,platform,description,language,region,member_count,health_status,health_last_checked_at,verification_status,quality_score,quality_grade,quality_issues,quality_checked_at,quality_reviewed_at,flag_reason,image_path,external_image_url").eq("status","published").order("quality_score",{ascending:true,nullsFirst:true}).limit(Math.max(1,Math.min(input.limit??60,100)));if(input.platform)q=q.eq("platform",input.platform);if(input.grade==="unscored")q=q.is("quality_grade",null);else if(input.grade)q=q.eq("quality_grade",input.grade);if(issue)q=q.ilike("flag_reason","%"+issue+"%");if(input.review==="outstanding")q=q.is("quality_reviewed_at",null);if(term)q=q.or("name.ilike.%"+term+"%,description.ilike.%"+term+"%,language.ilike.%"+term+"%,region.ilike.%"+term+"%,flag_reason.ilike.%"+term+"%");const{data,error}=await q;if(error)return[];const rows=(data??[]) as CommunityRow[];const categories=await categoryMap(rows.map(x=>x.id));return Promise.all(rows.map(async row=>({...row,category:categories.get(row.id)??null,imageUrl:row.image_path?await getPublishedCommunityImageUrl(row.image_path):null,issues:issueList(row.quality_issues)})));}
export async function getQualityCommunityForAdmin(id:string):Promise<AdminCommunityItem|null>{const s=createAdminSupabaseClient();const{data,error}=await s.from("communities").select("*").eq("id",id).eq("status","published").maybeSingle();if(error||!data)return null;const categories=await categoryMap([id]);let ownerEmail:string|null=null;if(data.owner_user_id){const result=await s.auth.admin.getUserById(data.owner_user_id);ownerEmail=result.data.user?.email??null;}return{...data,category:categories.get(id)??null,imageUrl:data.image_path?await getPublishedCommunityImageUrl(data.image_path):null,ownerEmail,sourceSubmissionCreatedAt:null,viewsRecent:0,joinClicksRecent:0,ctrRecent:0};}
