import { requireAdminUser } from "@/lib/supabase/auth";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";
import { updateCommunityMonetization } from "@/features/moderation/monetization-actions";
import { ControllerShell } from "@/components/admin/controller-shell";

type Props={searchParams:Promise<{status?:string}>};
function label(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());}
export default async function AdminMonetizationPage({searchParams}:Props){await requireAdminUser();const admin=createAdminSupabaseClient() as any;const{data:communities}=await admin.from("communities").select("id,name,slug,platform,status,verification_status,health_status,owner_user_id").not("owner_user_id","is",null).order("updated_at",{ascending:false}).limit(200);const ids=(communities??[]).map((c:any)=>c.id);const{data:monetization}=ids.length?await admin.from("community_monetization").select("*").in("community_id",ids):{data:[]};const byId=new Map<string,any>((monetization??[]).map((m:any)=>[m.community_id,m]));const query=await searchParams;return <ControllerShell active="monetization" title="Community Rewards" description="Manage monetization eligibility from real community trust signals."><section className="admin-section">{query.status==="updated"&&<p className="form-message success">Eligibility state updated.</p>}{query.status==="invalid"&&<p className="form-message error">Invalid eligibility request.</p>}{(communities??[]).map((c:any)=>{const m=byId.get(c.id)??{};return <article className="admin-record-card" key={c.id}><div className="admin-record-main"><div className="admin-record-heading"><span className={`admin-status-badge ${m.status??"not_eligible"}`}>{label(m.status??"not_eligible")}</span><h3>{c.name}</h3><p>{label(c.platform)} · Verification: {label(c.verification_status)} · Health: {label(c.health_status)}</p></div><dl className="admin-meta-grid"><div><dt>Readiness</dt><dd>{Number(m.readiness_score??0)}%</dd></div><div><dt>Owner</dt><dd>{c.owner_user_id?"Assigned":"Unclaimed"}</dd></div></dl></div><aside className="admin-actions-panel"><form action={updateCommunityMonetization}><input type="hidden" name="communityId" value={c.id}/><input type="hidden" name="status" value="eligible"/><input name="note" maxLength={2000} placeholder="Optional reason"/><button className="primary-button form-submit" type="submit">Mark eligible</button></form><form action={updateCommunityMonetization}><input type="hidden" name="communityId" value={c.id}/><input type="hidden" name="status" value="pending"/><button className="admin-secondary" type="submit">Set pending</button></form><form action={updateCommunityMonetization}><input type="hidden" name="communityId" value={c.id}/><input type="hidden" name="status" value="not_eligible"/><button className="admin-secondary" type="submit">Not eligible</button></form><form action={updateCommunityMonetization}><input type="hidden" name="communityId" value={c.id}/><input type="hidden" name="status" value="suspended"/><button className="admin-danger" type="submit">Suspend</button></form></aside></article>})}{!(communities??[]).length&&<div className="admin-empty"><strong>No claimed communities yet.</strong><p>Approved ownership claims will appear here.</p></div>}</section></ControllerShell>;
}
