import { logoutAdmin } from "@/features/auth/actions";
import { approveSubmission, rejectSubmission } from "@/features/moderation/actions";
import { getPendingSubmissions } from "@/features/moderation/data-access";
import { requireAdminUser } from "@/lib/supabase/auth";

type AdminPageProps = { searchParams: Promise<{ status?: string }> };

export default async function AdminPage({ searchParams }: AdminPageProps) {
  await requireAdminUser();
  const [submissions, { status }] = await Promise.all([getPendingSubmissions(), searchParams]);
  return <main className="admin-page"><header className="admin-header"><div><p className="eyebrow">CHATSCOUT ADMIN</p><h1>Pending community submissions</h1></div><form action={logoutAdmin}><button className="admin-sign-out" type="submit">Sign out</button></form></header><section className="admin-coming-soon" aria-labelledby="coming-soon-title"><div><p className="eyebrow">PLANNED TOOLS</p><h2 id="coming-soon-title">Coming soon</h2></div><div className="admin-coming-soon-grid"><article><h3>Community Analytics</h3><p>Coming soon</p></article><article><h3>Monetization Opportunities</h3><p>Future tools to help eligible communities discover relevant earning opportunities.</p></article><article><h3>Brand Opportunities</h3><p>Coming soon</p></article></div></section>{status && <p className={`form-message ${status === "approved" || status === "rejected" ? "success" : "error"}`}>{status === "approved" ? "Community approved and published." : status === "rejected" ? "Submission rejected." : "Unable to complete that review action."}</p>}{submissions === null ? <p className="form-message error">Submissions are temporarily unavailable.</p> : submissions.length === 0 ? <p className="form-message">No pending submissions.</p> : <section className="submission-list">{submissions.map((submission) => <article className="submission-card" key={submission.id}><div><h2>{submission.community_name}</h2><p>{submission.description}</p><dl><div><dt>Category</dt><dd>{submission.category ?? "—"}</dd></div><div><dt>Language</dt><dd>{submission.language ?? "—"}</dd></div><div><dt>Region</dt><dd>{submission.region ?? "—"}</dd></div><div><dt>Members</dt><dd>{submission.approximate_member_count?.toLocaleString("en-IN") ?? "—"}</dd></div><div><dt>Invite</dt><dd><a href={submission.invite_url} target="_blank" rel="noreferrer">Open Instagram invite</a></dd></div><div><dt>Contact</dt><dd>{submission.submitter_contact ?? "—"}</dd></div></dl></div><form className="review-form"><input type="hidden" name="submissionId" value={submission.id} /><label>Review notes<textarea name="reviewNotes" maxLength={2000} rows={3} /></label><div><button className="primary-button form-submit" formAction={approveSubmission}>Approve &amp; publish</button><button className="admin-reject" formAction={rejectSubmission}>Reject</button></div></form></article>)}</section>}</main>;
}
