import Link from 'next/link';
import { requireAdminUser } from '@/lib/supabase/auth';
import { createAdminSupabaseClient } from '@/lib/supabase/admin';
import { ControllerShell } from '@/components/admin/controller-shell';
import { controllerCampaignAction } from '@/features/brand/actions';

const label=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default async function AdminCampaignsPage(){
 await requireAdminUser();const db=createAdminSupabaseClient() as any;
 const [{data:campaigns},{data:participations},{data:submissions}]=await Promise.all([
  db.from('campaigns').select('id,title,status,total_budget,reward_per_community,created_at,application_deadline,brand_user_id').order('updated_at',{ascending:false}).limit(200),
  db.from('campaign_participations').select('id,campaign_id,status,reward_status,committed_reward,community_id').order('updated_at',{ascending:false}).limit(500),
  db.from('campaign_submissions').select('id,participation_id,status,revision_count,submitted_at').order('submitted_at',{ascending:false}).limit(500)
 ]);
 const pBy=new Map<string,any[]>();for(const p of participations??[])pBy.set(p.campaign_id,[...(pBy.get(p.campaign_id)??[]),p]);
 const pendingReview=(campaigns??[]).filter((c:any)=>c.status==='pending_review').length;const active=(campaigns??[]).filter((c:any)=>c.status==='active').length;const underReview=(submissions??[]).filter((s:any)=>s.status==='submitted').length;const rewards=(participations??[]).filter((p:any)=>p.reward_status==='approved').length;
 return <ControllerShell active="campaigns" title="Campaign Oversight" description="Platform-level visibility into active execution, submissions and reward approvals."><section className="admin-section"><div className="metrics"><div><span>Active campaigns</span><b>{active}</b><small>Currently running</small></div><div><span>Pending review</span><b>{pendingReview}</b><small>Campaign launches</small></div><div><span>Proof under review</span><b>{underReview}</b><small>Submitted deliverables</small></div><div><span>Rewards approved</span><b>{rewards}</b><small>Ledger credits</small></div></div>{(campaigns??[]).length?<div style={{display:'grid',gap:12,marginTop:18}}>{campaigns.map((c:any)=>{const ps=pBy.get(c.id)??[];const completed=ps.filter(p=>p.status==='completed').length;const reviewCount=(submissions??[]).filter((s:any)=>ps.some(p=>p.id===s.participation_id)&&s.status==='submitted').length;return <article className="admin-record-card" key={c.id}><div className="admin-record-main"><div className="admin-record-heading"><span className="admin-status-badge">{label(c.status)}</span><h3>{c.title}</h3><p>{ps.length} participations · {completed} completed · {reviewCount} proof items awaiting brand review</p></div><dl className="admin-meta-grid"><div><dt>Budget</dt><dd>₹{Number(c.total_budget??0).toLocaleString('en-IN')}</dd></div><div><dt>Reward/community</dt><dd>₹{Number(c.reward_per_community??ps[0]?.committed_reward??0).toLocaleString('en-IN')}</dd></div><div><dt>Deadline</dt><dd>{c.application_deadline?new Date(c.application_deadline).toLocaleDateString('en-IN'):'—'}</dd></div></dl></div><aside className="admin-actions-panel">{c.status==='pending_review'&&<form action={controllerCampaignAction}><input type="hidden" name="campaignId" value={c.id}/><input type="hidden" name="status" value="active"/><button className="primary-button" type="submit">Activate</button></form>}{c.status==='active'&&<form action={controllerCampaignAction}><input type="hidden" name="campaignId" value={c.id}/><input type="hidden" name="status" value="paused"/><button className="admin-secondary" type="submit">Pause</button></form>}{c.status==='paused'&&<form action={controllerCampaignAction}><input type="hidden" name="campaignId" value={c.id}/><input type="hidden" name="status" value="active"/><button className="primary-button" type="submit">Resume</button></form>}<span className="admin-meta-note">Brand submission review remains in the brand workspace.</span></aside></article>})}</div>:<div className="admin-empty"><strong>No campaigns.</strong><p>No brand has created a campaign yet.</p></div>}</section><section className="admin-section"><div className="admin-empty"><strong>Controller boundary</strong><p>Controller provides platform oversight and state controls. Brands approve/reject proof and the reward engine writes the existing earnings ledger.</p><Link className="admin-secondary" href="/admin/audit">View audit log →</Link></div></section></ControllerShell>;
}
