"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createServerAuthClient, requireAdminUser } from "@/lib/supabase/auth";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";

function text(form:FormData,key:string,fallback=""){return String(form.get(key)??fallback).trim();}
function money(v:string){if(!v)return null;const n=Number(v);return Number.isFinite(n)&&n>=0?n:null;}
function list(form:FormData,key:string){return text(form,key).split(",").map(v=>v.trim()).filter(Boolean);}
function num(v:string){if(!v)return null;const n=Number(v);return Number.isFinite(n)&&n>=0?Math.floor(n):null;}
function parseDeliverables(raw:string){if(!raw)return [];let parsed:unknown;try{parsed=JSON.parse(raw);}catch{throw new Error("Deliverables data is invalid.");}if(!Array.isArray(parsed)||parsed.length>20)throw new Error("A campaign may contain up to 20 deliverables.");return parsed.map((v:any,i)=>({title:String(v?.title??"").trim(),description:String(v?.description??"").trim(),type:String(v?.type??"other"),required:v?.required!==false,deadline:v?.deadline?String(v.deadline):null,reward_amount:money(String(v?.rewardAmount??"")),display_order:i,instructions:String(v?.instructions??"").trim()||null,required_text:String(v?.requiredText??"").trim()||null,destination_url:String(v?.destinationUrl??"").trim()||null,tracking_url:String(v?.trackingUrl??"").trim()||null,content_requirements:String(v?.contentRequirements??"").trim()||null,prohibited_modifications:String(v?.prohibitedModifications??"").trim()||null,timing:String(v?.timing??"").trim()||null,submission_requirements:String(v?.submissionRequirements??"").trim()||null})).filter(v=>v.title);}
async function currentUser(){const auth=await createServerAuthClient();const {data:{user}}=await auth.auth.getUser();return user;}

export async function saveBrandProfile(form:FormData){
 const user=await currentUser();if(!user)redirect('/brand/login');const companyName=text(form,'companyName'),description=text(form,'description');
 if(companyName.length<2||description.length<10)throw new Error('Please provide a valid brand name and description.');
 const db=createAdminSupabaseClient() as any;const {error}=await db.from('brand_profiles').upsert({user_id:user.id,company_name:companyName,slug:text(form,'slug')||null,logo_url:text(form,'logoUrl')||null,website:text(form,'website')||null,description,industry:text(form,'industry')||null,contact_email:text(form,'contactEmail')||user.email||null,contact_name:text(form,'contactName')||null,verification_status:'pending'},{onConflict:'user_id'});
 if(error)throw new Error(error.message);revalidatePath('/brand');revalidatePath('/brand/settings');redirect('/brand');
}

export async function saveCampaign(form:FormData){
 const user=await currentUser();if(!user)redirect('/brand/login');
 const title=text(form,'title'),description=text(form,'description'),objective=text(form,'objective');if(title.length<3||description.length<10||objective.length<3)throw new Error('Complete the campaign basics before saving.');
 const budget=money(text(form,'budget'))??0,reward=money(text(form,'rewardPerCommunity')),model=text(form,'rewardModel','fixed');if(reward!=null&&reward>budget&&model==='fixed')throw new Error('Reward per community cannot exceed the total budget for a fixed-reward campaign.');
 const db=createAdminSupabaseClient() as any;const id=text(form,'id');
 if(id){const {data:existing}=await db.from('campaigns').select('id,status').eq('id',id).eq('brand_user_id',user.id).maybeSingle();if(!existing)throw new Error('Campaign not found.');if(!['draft','pending_review'].includes(existing.status))throw new Error('Active or completed campaigns cannot be edited.');}
 const payload={brand_user_id:user.id,title,description,objective,category_id:text(form,'categoryId')||null,target_platforms:list(form,'platforms'),target_languages:list(form,'languages'),target_regions:list(form,'regions'),min_member_count:num(text(form,'minMembers')),max_member_count:num(text(form,'maxMembers')),require_verified:form.get('requireVerified')==='on',require_healthy:form.get('requireHealthy')==='on',total_budget:budget,reward_per_community:reward,reward_min:money(text(form,'rewardMin')),reward_max:money(text(form,'rewardMax')),reward_model:model,starts_at:text(form,'startsAt')||null,ends_at:text(form,'endsAt')||null,application_deadline:text(form,'deadline')||null,requirements:text(form,'requirements')||null,deliverables_description:text(form,'deliverables')||null,instructions:text(form,'instructions')||null};
 const result=id?await db.from('campaigns').update(payload).eq('id',id).eq('brand_user_id',user.id).select('id').single():await db.from('campaigns').insert(payload).select('id').single();if(result.error||!result.data)throw new Error(result.error?.message??'Unable to save campaign.');const campaignId=result.data.id;
 const deliverables=parseDeliverables(text(form,'deliverablesJson'));if(id){const {error}=await db.from('campaign_deliverables').delete().eq('campaign_id',campaignId);if(error)throw new Error(error.message);}if(deliverables.length){const {error}=await db.from('campaign_deliverables').insert(deliverables.map(v=>({...v,campaign_id:campaignId})));if(error)throw new Error(error.message);}
 revalidatePath('/brand');revalidatePath('/brand/campaigns');revalidatePath('/brand/communities');redirect('/brand/campaigns');
}

export async function submitCampaign(form:FormData){const user=await currentUser();if(!user)redirect('/brand/login');const db=createAdminSupabaseClient() as any;const {data:campaign}=await db.from('campaigns').select('id,total_budget,reward_per_community,reward_min').eq('id',text(form,'campaignId')).eq('brand_user_id',user.id).maybeSingle();if(!campaign)throw new Error('Campaign not found.');const {count}=await db.from('campaign_deliverables').select('id',{count:'exact',head:true}).eq('campaign_id',campaign.id);if(!count)throw new Error('Add at least one deliverable before submitting the campaign for review.');if(Number(campaign.total_budget)<=0||((campaign.reward_per_community??campaign.reward_min)??0)<=0)throw new Error('Configure a positive campaign reward before submitting.');const {error}=await db.rpc('change_campaign_status',{p_campaign_id:campaign.id,p_status:'pending_review'});if(error)throw new Error(error.message);revalidatePath('/brand/campaigns');revalidatePath('/admin/campaigns');}

export async function applyToCampaign(form:FormData){const user=await currentUser();if(!user)redirect('/submit/login?error=auth');const db=createAdminSupabaseClient() as any;const campaignId=text(form,'campaignId'),communityId=text(form,'communityId');const {data:adminRow}=await db.from('community_admins').select('community_id').eq('community_id',communityId).eq('user_id',user.id).maybeSingle();if(!adminRow)throw new Error('You do not manage this community.');const {data:campaign}=await db.from('campaigns').select('id,status,application_deadline').eq('id',campaignId).maybeSingle();if(!campaign||campaign.status!=='active'||(campaign.application_deadline&&new Date(campaign.application_deadline)<new Date()))throw new Error('This campaign is not accepting applications.');const {error}=await db.from('campaign_applications').insert({campaign_id:campaignId,community_id:communityId,admin_user_id:user.id,application_note:text(form,'note')||null,status:'pending'});if(error&&error.code!=='23505')throw new Error(error.message);revalidatePath('/dashboard/rewards');revalidatePath('/dashboard/notifications');}

export async function reviewApplication(form:FormData){const user=await currentUser();if(!user)redirect('/brand/login');const status=text(form,'status');if(!['approved','rejected','shortlisted'].includes(status))throw new Error('Invalid application status.');const db=createAdminSupabaseClient() as any;const {error}=await db.rpc('review_campaign_application',{p_application_id:text(form,'applicationId'),p_status:status});if(error)throw new Error(error.message);revalidatePath('/brand/applications');revalidatePath('/dashboard/rewards');void user;}

export async function controllerCampaignAction(form:FormData){const adminUser=await requireAdminUser();const id=text(form,'campaignId'),status=text(form,'status');if(!['active','paused','completed','cancelled'].includes(status))throw new Error('Invalid campaign action.');const db=createAdminSupabaseClient() as any;const {data:c}=await db.from('campaigns').select('status').eq('id',id).maybeSingle();if(!c)throw new Error('Campaign not found.');if(status==='active'){const {count}=await db.from('campaign_deliverables').select('id',{count:'exact',head:true}).eq('campaign_id',id).eq('required',true);if(!count)throw new Error('Campaign needs at least one required deliverable before activation.');}const allowed=(c.status==='pending_review'&&['active','cancelled'].includes(status))||(c.status==='active'&&['paused','completed','cancelled'].includes(status))||(c.status==='paused'&&['active','completed','cancelled'].includes(status));if(!allowed)throw new Error('Invalid controller state transition.');const {error}=await db.from('campaigns').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw new Error(error.message);await db.from('campaign_execution_audit').insert({campaign_id:id,actor_user_id:adminUser.id,actor_type:'controller',action:'campaign_status_changed',details:{status}});revalidatePath('/admin/campaigns');revalidatePath('/brand/campaigns');}

export async function reviewCampaignSubmission(form:FormData){const user=await currentUser();if(!user)redirect('/brand/login');const status=text(form,'status'),reason=text(form,'reason');if(!['approved','revision_required','rejected'].includes(status))throw new Error('Invalid review state.');const db=createAdminSupabaseClient() as any;const {error}=await db.rpc('review_campaign_submission',{p_submission_id:text(form,'submissionId'),p_status:status,p_reason:reason||null});if(error)throw new Error(error.message);revalidatePath('/brand/campaigns');revalidatePath('/brand/applications');revalidatePath('/dashboard/rewards');revalidatePath('/dashboard/notifications');void user;}
