import "server-only";
import { createServerAuthClient } from "@/lib/supabase/auth";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";
import { getPublishedCommunityImageUrl } from "@/lib/supabase/community-images";
import type { CommunityRow, Database } from "@/types/database";

type SubmissionRow = Database["public"]["Tables"]["submissions"]["Row"];

type OwnerCommunity = CommunityRow & { imageUrl: string | null; views: number; joins: number; ctr: number; monetizationStatus: string; readinessScore: number };
export type OwnerDashboardData = { user:{id:string;email:string|null;name:string;avatarUrl:string|null}; communities:OwnerCommunity[]; stats:{totalCommunities:number;published:number;pending:number;archived:number;views:number;joins:number;ctr:number;eligible:number;totalEarnings:number}; recentSubmissions:SubmissionRow[] };
function userDisplayName(user:{email?:string|null;user_metadata?:Record<string,unknown>}){const m=user.user_metadata??{};const name=typeof m.full_name==="string"?m.full_name.trim():"";if(name)return name;const given=typeof m.name==="string"?m.name.trim():"";if(given)return given;return user.email?.split("@")[0]??"Community owner";}
function avatarUrl(user:{user_metadata?:Record<string,unknown>}){const m=user.user_metadata??{};return typeof m.avatar_url==="string"?m.avatar_url:typeof m.picture==="string"?m.picture:null;}
async function authContext(){const auth=await createServerAuthClient();const{data:{user}}=await auth.auth.getUser();if(!user)return null;return{id:user.id,email:user.email??null,name:userDisplayName(user),avatarUrl:avatarUrl(user)};}
async function analyticsForCommunities(ids:string[]){if(!ids.length)return new Map<string,{views:number;joins:number}>();const supabase=createAdminSupabaseClient();const since=new Date(Date.now()-30*24*60*60*1000).toISOString();const{data}=await supabase.from("analytics_events").select("community_id,event_name").in("community_id",ids).gte("occurred_at",since).in("event_name",["community_view","join_click"]).limit(20000);const counts=new Map<string,{views:number;joins:number}>();for(const event of data??[]){if(!event.community_id)continue;const current=counts.get(event.community_id)??{views:0,joins:0};if(event.event_name==="community_view")current.views+=1;if(event.event_name==="join_click")current.joins+=1;counts.set(event.community_id,current);}return counts;}
export async function getOwnerDashboardData():Promise<OwnerDashboardData|null>{const user=await authContext();if(!user)return null;const supabase=createAdminSupabaseClient() as any;const[{data:communities},{data:submissions}]=await Promise.all([supabase.from("communities").select("*").eq("owner_user_id",user.id).order("created_at",{ascending:false}),supabase.from("submissions").select("*").eq("submitter_user_id",user.id).order("created_at",{ascending:false}).limit(12)]);const owned=communities??[];const ids=owned.map((c:any)=>c.id);const[{data:monetization},{data:ledger}]=await Promise.all([ids.length?supabase.from("community_monetization").select("community_id,status,readiness_score").in("community_id",ids):Promise.resolve({data:[]}),supabase.from("community_earnings_ledger").select("amount,status").eq("user_id",user.id)]);const monetizationMap=new Map<string,any>((monetization??[]).map((m:any)=>[m.community_id,m]));const analytics=await analyticsForCommunities(ids);const mapped=await Promise.all(owned.map(async(community:any)=>{const stats=analytics.get(community.id)??{views:0,joins:0};const m=monetizationMap.get(community.id)??{};return{...community,imageUrl:await getPublishedCommunityImageUrl(community.image_path),views:stats.views,joins:stats.joins,ctr:stats.views?Math.round((stats.joins/stats.views)*1000)/10:0,monetizationStatus:m.status??"not_eligible",readinessScore:Number(m.readiness_score??0)};}));const views=mapped.reduce((sum:number,item:any)=>sum+item.views,0),joins=mapped.reduce((sum:number,item:any)=>sum+item.joins,0);const totalEarnings=(ledger??[]).reduce((sum:number,item:any)=>item.status==="reversed"?sum:sum+Number(item.amount??0),0);return{user,communities:mapped,stats:{totalCommunities:mapped.length,published:mapped.filter((x:any)=>x.status==="published").length,pending:(submissions??[]).filter((x:any)=>x.status==="pending").length,archived:mapped.filter((x:any)=>x.status==="archived").length,views,joins,ctr:views?Math.round((joins/views)*1000)/10:0,eligible:mapped.filter((x:any)=>x.monetizationStatus==="eligible").length,totalEarnings},recentSubmissions:submissions??[]};}
export async function getCurrentOwnerProfile(){return await authContext();}
