import Link from "next/link";
import { CommunityGrid } from "@/components/community/community-grid";
import { Icon } from "@/components/ui/icon";
import { getPublishedCommunities, searchPublishedCommunities } from "@/features/communities/data-access";
import { toCommunityPresentation } from "@/features/communities/presentation";

const topics = ["BCA", "Coding", "Anime", "Jaipur", "JEE", "Gaming", "Delhi", "Entrepreneurs"];
const categoryIcons = ["⌘", "</>", "◉", "🎮", "✦", "•••"];

export async function DiscoveryHome({ searchTerm = "" }: { searchTerm?: string }) {
  const result = searchTerm ? await searchPublishedCommunities(searchTerm) : await getPublishedCommunities();
  const communities = result.data ? await Promise.all(result.data.map(toCommunityPresentation)) : [];
  const message = result.error ? "Communities are temporarily unavailable. Please try again later." : communities.length === 0 ? searchTerm ? "No communities match your search." : "No published communities are available yet." : null;
  return <main className="page-content"><section className="hero"><div className="hero-copy"><p className="eyebrow">DISCOVER YOUR NEXT CIRCLE</p><h1>Find the right <span>Instagram</span><br />Group Chat for you</h1><p className="hero-text">Search by interest, course, city or community and find people who get you.</p><form className="hero-search" role="search" action="/"><Icon name="search" /><input aria-label="Search group chats" name="q" defaultValue={searchTerm} placeholder="e.g. BCA students, Anime fans, Jaipur, Coding" /><button type="submit">Search <Icon name="arrow" size={17} /></button></form><div className="popular"><span>Popular:</span>{topics.map((topic) => <Link href={`/?q=${encodeURIComponent(topic)}`} key={topic}>{topic}</Link>)}</div></div><div className="hero-art" aria-hidden="true"><div className="hero-instagram"><Icon name="instagram" size={72} /></div><div className="hero-person person-one" /><div className="hero-person person-two" /><div className="hero-person person-three" /><span className="bubble bubble-one">♥</span><span className="bubble bubble-two">✦</span></div></section><section className="mobile-categories" aria-label="Popular categories">{["BCA", "Coding", "Anime", "Gaming", "JEE", "All"].map((category, index) => <Link href={`/?q=${encodeURIComponent(category)}`} key={category}><b>{categoryIcons[index]}</b><span>{category}</span></Link>)}</section><section className="trust-strip"><div><span className="trust-icon"><Icon name="spark" /></span><b>Curated discovery</b><small>Explore UI-only demo groups</small></div><div><span className="trust-icon"><Icon name="users" /></span><b>Find your people</b><small>By interests and communities</small></div><div><span className="trust-icon">↗</span><b>Simple next step</b><small>View a community before joining</small></div></section><section className="discover-section"><div className="section-heading"><div><p className="eyebrow">EXPLORE</p><h2>Top Matches <span>for you</span></h2></div><Link href="/#communities">View all <Icon name="arrow" size={16} /></Link></div>{message ? <p className="demo-notice">{message}</p> : <CommunityGrid communities={communities.slice(0, 3)} />}</section>{communities.length > 3 && <section className="discover-section trending-section" id="communities"><div className="section-heading"><div><p className="eyebrow">MORE TO EXPLORE</p><h2>Trending <span>right now</span></h2></div></div><CommunityGrid communities={communities.slice(3)} compact /></section>}</main>;
}
