"use server";
import crypto from "node:crypto";
import { redirect } from "next/navigation";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";
import { createServerAuthClient } from "@/lib/supabase/auth";
function value(formData:FormData,key:string,max:number,required=false){const raw=formData.get(key);const text=typeof raw==="string"?raw.trim():"";if((required&&!text)||text.length>max)return null;return text||null;}
export async function submitClaim(formData:FormData){const auth=await createServerAuthClient();const{data:{user}}=await auth.auth.getUser();if(!user)redirect("/submit/login?error=auth");const communityId=value(formData,"communityId",80,true),slug=value(formData,"slug",160,true),code=value(formData,"verificationCode",32,true);if(!communityId||!slug||!code)redirect("/");const supabase=createAdminSupabaseClient() as any;const{data:community}=await supabase.from("communities").select("id,claim_status").eq("id",communityId).maybeSingle();const claimStatus=String(community?.claim_status??"");if(!community||claimStatus==="claimed")redirect(`/community/${encodeURIComponent(slug)}`);const{data:existing}=await supabase.from("claim_requests").select("id").eq("community_id",communityId).eq("requesting_user_id",user.id).eq("status","pending").maybeSingle();if(existing)redirect(`/claim/${encodeURIComponent(slug)}?status=pending`);const{error}=await supabase.from("claim_requests").insert({community_id:communityId,requesting_user_id:user.id,verification_method:"bio_code",verification_code:code,status:"pending"});if(error)redirect(`/claim/${encodeURIComponent(slug)}?error=database`);await supabase.from("communities").update({claim_status:"pending_verification",updated_at:new Date().toISOString()}).eq("id",communityId).eq("claim_status","unclaimed");redirect(`/claim/${encodeURIComponent(slug)}?status=pending`);}
async function requireAdmin(){const auth=await createServerAuthClient();const{data:{user}}=await auth.auth.getUser();if(!user)redirect("/admin/login");const{isAuthorizedAdmin}=await import("@/lib/supabase/admin-authorization");if(!isAuthorizedAdmin(user.id))redirect("/admin/login");return user;}
export async function approveClaim(formData:FormData){const user=await requireAdmin();const id=value(formData,"claimRequestId",80,true);if(!id)return;const supabase=createAdminSupabaseClient() as any;const{data:request,error}=await supabase.rpc("approve_claim_request",{p_claim_request_id:id});if(error||!request)return;const r=request as{community_id:string;requesting_user_id:string};await supabase.from("admin_audit_log").insert({action:"edited",admin_user_id:user.id,community_id:r.community_id,note:`Community ownership claim approved. claim_request_id=${id}`});await supabase.from("owner_notifications").insert({user_id:r.requesting_user_id,title:"Community claim approved",message:"Your ownership claim was approved. You can now edit your community listing.",kind:"success",href:"/dashboard"});redirect("/admin/claims?resolved=approved");}
export async function rejectClaim(formData:FormData){const user=await requireAdmin();const id=value(formData,"claimRequestId",80,true);if(!id)return;const supabase=createAdminSupabaseClient() as any;const{data:request,error}=await supabase.rpc("reject_claim_request",{p_claim_request_id:id});if(error||!request)return;const r=request as{community_id:string;requesting_user_id:string};await supabase.from("admin_audit_log").insert({action:"edited",admin_user_id:user.id,community_id:r.community_id,note:`Community ownership claim rejected. claim_request_id=${id}`});await supabase.from("owner_notifications").insert({user_id:r.requesting_user_id,title:"Community claim rejected",message:"Your ownership claim was not approved. You can submit a new claim after checking the verification instructions.",kind:"warning",href:"/"});redirect("/admin/claims?resolved=rejected");}
export async function newClaimCode(){return `CS-${crypto.randomBytes(2).toString("hex").toUpperCase()}`;}
