import Link from 'next/link';
import { redirect } from 'next/navigation';
import { getOwnerRewardsData } from '@/features/owner-v2/data-access';
import { createServerAuthClient } from '@/lib/supabase/auth';
import { createAdminSupabaseClient } from '@/lib/supabase/admin';
import { applyToCampaign } from '@/features/brand/actions';
import styles from '../owner.module.css';

const label=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const statusClass=(v:string)=>v==='completed'?styles.success:v==='rejected'||v==='expired'?styles.warning:styles.neutral;
export default async function OwnerRewardsPage(){
 const data=await getOwnerRewardsData();if(!data)redirect('/submit/login?error=auth');const auth=await createServerAuthClient();const {data:{user}}=await auth.auth.getUser();const db=createAdminSupabaseClient() as any;
 const ownedIds=data.communities.filter(c=>c.monetizationStatus==='eligible'&&c.claimStatus==='claimed').map(c=>c.id);
 const {data:campaigns}=await db.from('campaigns').select('id,title,objective,reward_per_community,reward_min,application_deadline,status,target_platforms,require_verified,require_healthy').eq('status','active').order('application_deadline',{ascending:true});
 const {data:participations}=await db.from('campaign_participations').select('id,campaign_id,community_id,status,reward_status,committed_reward').eq('admin_user_id',user?.id??'').order('updated_at',{ascending:false});
 const {data:apps}=ownedIds.length?await db.from('campaign_applications').select('campaign_id,community_id,status').eq('admin_user_id',user?.id??'').in('community_id',ownedIds):{data:[]};const applied=new Set((apps??[]).map((a:any)=>`${a.campaign_id}:${a.community_id}`));
 const pendingRewards=(participations??[]).filter((p:any)=>p.reward_status==='pending').reduce((s:number,p:any)=>s+Number(p.committed_reward??0),0);const approvedRewards=(participations??[]).filter((p:any)=>p.reward_status==='approved').reduce((s:number,p:any)=>s+Number(p.committed_reward??0),0);
 return <main className="page-content"><header className={styles.header}><div><Link href="/dashboard" className="back-link">← Back to dashboard</Link><p className="eyebrow">COMMUNITY REWARDS</p><h1>Campaign execution & earnings</h1><p>Your state and earnings come from real participation and ledger records. Approved rewards are internal Community Rewards credits, not bank/UPI transfers.</p></div></header>
 <section className={styles.metrics}><div><span>Active opportunities</span><b>{campaigns?.length??0}</b><small>Real active campaigns</small></div><div><span>Participations</span><b>{participations?.length??0}</b><small>Selected / executing</small></div><div><span>Pending rewards</span><b>₹{pendingRewards.toLocaleString('en-IN',{maximumFractionDigits:2})}</b><small>Not approved yet</small></div><div><span>Approved rewards</span><b>₹{approvedRewards.toLocaleString('en-IN',{maximumFractionDigits:2})}</b><small>Ledger-approved credits</small></div></section>
 <section className={styles.section}><div className={styles.sectionHeading}><div><p className="eyebrow">MY CAMPAIGNS</p><h2>Execution status</h2></div></div>{participations?.length?<div className={styles.grid}>{participations.map((p:any)=><article className={styles.card} key={p.id}><div className={styles.cardBody}><div className={styles.cardTop}><span className={`${styles.badge} ${statusClass(p.status)}`}>{label(p.status)}</span><span className={styles.badge}>{label(p.reward_status)}</span></div><h3>{(campaigns??[]).find((c:any)=>c.id===p.campaign_id)?.title??'Campaign'}</h3><div className={styles.meta}>Committed reward ₹{Number(p.committed_reward??0).toLocaleString('en-IN')}</div><Link className={styles.view} href={`/dashboard/rewards/${p.campaign_id}`}>Open campaign workspace →</Link></div></article>)}</div>:<div className={styles.empty}><h3>No participation records yet.</h3><p>Applications and approved selections will appear here from real campaigns.</p></div>}</section>
 <section className={styles.section}><div className={styles.sectionHeading}><div><p className="eyebrow">LIVE OPPORTUNITIES</p><h2>Available campaigns</h2></div></div>{campaigns?.length&&ownedIds.length?<div className={styles.grid}>{campaigns.map((c:any)=>{const eligible=data.communities.filter(comm=>ownedIds.includes(comm.id)&&(!c.target_platforms?.length||c.target_platforms.includes(comm.platform))&&(!c.require_verified||comm.verificationStatus==='verified')&&(!c.require_healthy||comm.healthStatus==='healthy'));return <article className={styles.card} key={c.id}><div className={styles.cardBody}><div className={styles.cardTop}><span className={styles.badge}>Active</span><span className={styles.badge}>{c.reward_per_community?`₹${Number(c.reward_per_community).toLocaleString('en-IN')}`:'Configured reward'}</span></div><h3>{c.title}</h3><p>{c.objective}</p><div className={styles.meta}>{eligible.length} eligible owned communit{eligible.length===1?'y':'ies'}{c.application_deadline?` · Deadline ${new Date(c.application_deadline).toLocaleDateString('en-IN')}`:''}</div><div style={{display:'grid',gap:8,marginTop:10}}>{eligible.map((comm:any)=>{const key=`${c.id}:${comm.id}`;return applied.has(key)?<span key={comm.id} className={styles.badge}>{comm.name}: {label((apps??[]).find((a:any)=>a.campaign_id===c.id&&a.community_id===comm.id)?.status??'applied')}</span>:<form action={applyToCampaign} key={comm.id}><input type="hidden" name="campaignId" value={c.id}/><input type="hidden" name="communityId" value={comm.id}/><button className="primary-button" type="submit">Apply with {comm.name}</button></form>})}</div></div></article>})}</div>:<div className={styles.empty}><h3>{ownedIds.length?'No campaigns available yet.':'No eligible owned community.'}</h3><p>{ownedIds.length?'No active campaign currently matches your community.':'Complete ownership, verification and trust requirements before opportunities appear.'}</p></div>}</section>
 <section className={styles.section}><div className={styles.sectionHeading}><div><p className="eyebrow">EARNINGS</p><h2>Reward progression</h2></div></div><div className={styles.monetization}><article><span>Pending</span><h3>₹{pendingRewards.toLocaleString('en-IN',{maximumFractionDigits:2})}</h3><p>Selected/in-progress rewards awaiting brand acceptance.</p></article><article><span>Approved</span><h3>₹{approvedRewards.toLocaleString('en-IN',{maximumFractionDigits:2})}</h3><p>Internal ledger credits created after required deliverables are approved.</p></article><article><span>Paid</span><h3>₹0</h3><p>Phase 3 does not execute payouts. Phase 4 handles payment processing.</p></article></div></section>
 </main>;
}
