import Link from 'next/link';
import { redirect } from 'next/navigation';
import { getOwnerRewardsData } from '@/features/owner-v2/data-access';
import { createServerAuthClient } from '@/lib/supabase/auth';
import { createAdminSupabaseClient } from '@/lib/supabase/admin';
import { applyToCampaign } from '@/features/brand/actions';
import styles from '../owner.module.css';

function statusLabel(value:string){return value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());}
function statusClass(value:string){return value==='eligible'?styles.success:value==='suspended'?styles.warning:styles.neutral;}

export default async function OwnerRewardsPage(){
  const data=await getOwnerRewardsData();
  if(!data)redirect('/submit/login?error=auth');
  const auth=await createServerAuthClient();
  const {data:{user}}=await auth.auth.getUser();
  const db=createAdminSupabaseClient() as any;
  const communityIds=data.communities.filter(c=>c.monetizationStatus==='eligible'&&c.claimStatus==='claimed').map(c=>c.id);
  const {data:campaigns}=await db.from('campaigns').select('id,title,objective,description,total_budget,reward_per_community,reward_min,reward_max,application_deadline,target_platforms,target_languages,target_regions,require_verified,require_healthy,status').eq('status','active').order('application_deadline',{ascending:true});
  const {data:existingApplications}=communityIds.length?await db.from('campaign_applications').select('campaign_id,community_id,status').eq('admin_user_id',user?.id??'').in('community_id',communityIds):{data:[]};
  const applied=new Set((existingApplications??[]).map((a:any)=>`${a.campaign_id}:${a.community_id}`));
  const eligibleCommunities=data.communities.filter(c=>communityIds.includes(c.id));
  return <main className="page-content"><header className={styles.header}><div><Link href="/dashboard" className="back-link">← Back to dashboard</Link><p className="eyebrow">COMMUNITY REWARDS</p><h1>Campaign opportunities</h1><p>Only real active campaigns are shown. Eligibility comes from your existing ownership, verification and trust signals.</p></div></header>
    <section className={styles.metrics}><div><span>Communities</span><b>{data.communities.length}</b><small>Owned listings</small></div><div><span>Eligible</span><b>{eligibleCommunities.length}</b><small>Eligible for opportunities</small></div><div><span>Total earnings</span><b>₹{data.totalEarnings.toLocaleString('en-IN',{maximumFractionDigits:2})}</b><small>Recorded ledger only</small></div><div><span>Available</span><b>₹{data.availableEarnings.toLocaleString('en-IN',{maximumFractionDigits:2})}</b><small>Approved or available</small></div></section>
    <section className={styles.section}><div className={styles.sectionHeading}><div><p className="eyebrow">READINESS</p><h2>Your communities</h2></div></div>{data.communities.length?<div className={styles.grid}>{data.communities.map(c=><article className={styles.card} key={c.id}><div className={styles.cardBody}><div className={styles.cardTop}><span className={`${styles.badge} ${statusClass(c.monetizationStatus)}`}>{statusLabel(c.monetizationStatus)}</span><span className={`${styles.badge} ${c.verificationStatus==='verified'?styles.success:styles.warning}`}>{statusLabel(c.verificationStatus)}</span></div><h3>{c.name}</h3><div className={styles.meta}>{statusLabel(c.platform)} · {statusLabel(c.status)}</div><div className="owner-readiness"><div className="owner-readiness-bar"><span style={{width:`${c.readinessScore}%`}} /></div><strong>{c.readinessScore}% readiness</strong></div><div className="owner-requirements"><span>{c.requirements.listed?'✓':'○'} Listed</span><span>{c.requirements.profile?'✓':'○'} Profile complete</span><span>{c.requirements.ownership?'✓':'○'} Ownership verified</span><span>{c.requirements.trust?'✓':'○'} Trust signals</span></div></div></article>)}</div>:<div className={styles.empty}><h3>Add your first community</h3><p>Verified communities can later become eligible for Community Rewards.</p><Link className="primary-button list-button" href="/submit">List Your GC</Link></div>}</section>
    <section className={styles.section}><div className={styles.sectionHeading}><div><p className="eyebrow">LIVE OPPORTUNITIES</p><h2>Available campaigns</h2><p>Applications are one-per-campaign per community and remain pending until the brand reviews them.</p></div></div>{campaigns?.length&&eligibleCommunities.length?<div className={styles.grid}>{campaigns.map((c:any)=>{const matching=eligibleCommunities.filter(comm=>{if((c.target_platforms??[]).length&&!c.target_platforms.includes(comm.platform))return false;if(c.require_verified&&comm.verificationStatus!=='verified')return false;return true;});return <article className={styles.card} key={c.id}><div className={styles.cardBody}><div className={styles.cardTop}><span className={styles.badge}>Active</span><span className={styles.badge}>{c.reward_per_community?`₹${Number(c.reward_per_community).toLocaleString('en-IN')}`:(c.reward_min!=null?`₹${Number(c.reward_min).toLocaleString('en-IN')}+`:'Reward details')}</span></div><h3>{c.title}</h3><p>{c.objective}</p><div className={styles.meta}>{matching.length} eligible owned communit{matching.length===1?'y':'ies'}{c.application_deadline?` · Deadline ${new Date(c.application_deadline).toLocaleDateString('en-IN')}`:''}</div><div className={styles.cardLinks}>{matching.map((comm:any)=>{const key=`${c.id}:${comm.id}`;return applied.has(key)?<span key={comm.id} className={styles.badge}>{comm.name}: {statusLabel((existingApplications??[]).find((a:any)=>a.campaign_id===c.id&&a.community_id===comm.id)?.status??'applied')}</span>:<form action={applyToCampaign} key={comm.id}><input type="hidden" name="campaignId" value={c.id}/><input type="hidden" name="communityId" value={comm.id}/><button className="primary-button" type="submit">Apply with {comm.name}</button></form>})}</div></div></article>})}</div>:<div className={styles.empty}><h3>No campaigns available yet.</h3><p>{eligibleCommunities.length?'No active campaign currently matches your eligible communities.':'No owned community is currently eligible for campaign opportunities.'}</p></div>}</section>
  </main>;
}
