import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireBrand } from '@/lib/brand/authorization';
import { createAdminSupabaseClient } from '@/lib/supabase/admin';
import { reviewCampaignSubmission } from '@/features/brand/actions';
import { getCampaignProofSignedUrl } from '@/lib/supabase/campaign-proof';

const label=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());

export default async function BrandCampaignSubmissions({params}:{params:Promise<{id:string}>}){
 const brand=await requireBrand();const {id}=await params;const db=createAdminSupabaseClient() as any;
 const {data:c}=await db.from('campaigns').select('*').eq('id',id).eq('brand_user_id',brand.user.id).maybeSingle();if(!c)notFound();
 const {data:rows}=await db.from('campaign_participations').select('id,status,reward_status,committed_reward,admin_user_id,community_id,application_id,communities!inner(id,name,slug,platform,member_count,language,region),campaign_applications(id,status,application_note)').eq('campaign_id',id).order('created_at',{ascending:false});
 const ids=(rows??[]).map((r:any)=>r.id);const {data:deliverables}=ids.length?await db.from('campaign_deliverables').select('*').eq('campaign_id',id).order('display_order'): {data:[]};const dBy=new Map((deliverables??[]).map((d:any)=>[d.id,d]));const submissions=ids.length? (await db.from('campaign_submissions').select('*').in('participation_id',ids).order('version_no',{ascending:false})).data??[]:[];const latest=new Map<string,any>();for(const s of submissions)if(!latest.has(`${s.participation_id}:${s.deliverable_id}`))latest.set(`${s.participation_id}:${s.deliverable_id}`,s);
 const signed=new Map<string,string>();for(const s of Array.from(latest.values()))if(s.file_path){const url=await getCampaignProofSignedUrl(s.file_path);if(url)signed.set(s.id,url);}
 const pending=submissions.filter((s:any)=>s.status==='submitted').length,revision=submissions.filter((s:any)=>s.status==='revision_required').length,approved=submissions.filter((s:any)=>s.status==='approved').length;
 return <main className="page-content"><header className="owner-header"><div><Link href="/brand/campaigns" className="back-link">← Campaigns</Link><p className="eyebrow">CAMPAIGN SUBMISSIONS</p><h1>{c.title}</h1><p>Review deliverables and proof from actual campaign participants. Approval accepts the work and, when all required deliverables are approved, credits the configured reward to the existing ledger.</p></div></header>
 <section className="metrics"><div><span>Selected</span><b>{rows?.length??0}</b><small>Participation records</small></div><div><span>Pending review</span><b>{pending}</b><small>Submitted proof</small></div><div><span>Revision requested</span><b>{revision}</b><small>Needs resubmission</small></div><div><span>Approved proof</span><b>{approved}</b><small>Accepted submissions</small></div></section>
 <section className="section">{rows?.length?<div className="grid">{rows.map((p:any)=>{const dRows=(deliverables??[]).filter((d:any)=>d);return <article className="card" key={p.id}><div className="cardBody"><div className="cardTop"><span className="badge">{label(p.status)}</span><span className="badge">₹{Number(p.committed_reward??0).toLocaleString('en-IN')}</span></div><h3>{p.communities.name}</h3><div className="meta">{p.communities.platform} · {p.communities.member_count?.toLocaleString('en-IN')??'—'} members · {p.communities.language??'—'}</div><div className="meta">Reward: {label(p.reward_status)}</div>{p.campaign_applications?.[0]?.application_note&&<p>{p.campaign_applications[0].application_note}</p>}<div style={{display:'grid',gap:12,marginTop:12}}>{dRows.map((d:any)=>{const s=latest.get(`${p.id}:${d.id}`);const url=signed.get(s?.id??'');return <div key={d.id} style={{padding:12,border:'1px solid var(--line)',borderRadius:10}}><div className="community-title-row"><strong>{d.title}</strong><span className="demo-pill">{label(s?.status??'not started')}</span></div>{s?.content&&<p>{s.content}</p>}{s?.metric_value!=null&&<p className="meta">Metric: {s.metric_value}</p>}{url&&<p><a className="view" href={url} target="_blank" rel="noreferrer">View private proof ↗</a></p>}{s?.review_reason&&<p className="form-message error">{s.review_reason}</p>}{s&&s.status==='submitted'&&<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><form action={reviewCampaignSubmission}><input type="hidden" name="submissionId" value={s.id}/><input type="hidden" name="status" value="approved"/><button className="primary-button list-button" type="submit">Approve</button></form><form action={reviewCampaignSubmission} style={{display:'flex',gap:6,flexWrap:'wrap'}}><input type="hidden" name="submissionId" value={s.id}/><input type="hidden" name="status" value="revision_required"/><input name="reason" required placeholder="Revision reason"/><button className="admin-secondary" type="submit">Request revision</button></form><form action={reviewCampaignSubmission}><input type="hidden" name="submissionId" value={s.id}/><input type="hidden" name="status" value="rejected"/><input name="reason" placeholder="Rejection reason"/><button className="admin-danger" type="submit">Reject</button></form></div>}</div>})}</div></div></article>})}</div>:<div className="empty"><h3>No participations yet.</h3><p>Approved applications will appear here after a real community is selected.</p></div>}</section>
 <section className="section"><div className="empty"><h3>Execution progress is live-data only.</h3><p>Counts above come from actual participation and submission records. No reach, conversion or performance figures are fabricated.</p></div></section>
 </main>;
}
